#!/bin/bash
set -euo pipefail

# Workdir defined at Dockerfile
readonly WORKDIR="/var/www/html"
# Application service at docker-compose.yml
readonly DOCKER_SERVICE_NAME="app"
# Container name for app service at docker-compose.yml
readonly DOCKER_SERVICE_CONTAINER_NAME="laravel_from_scratch"

function configure_xdebug() {
  cp _infra/configs/xdebug-base.ini _infra/configs/xdebug.ini

  if [[ "$(uname -s)" = "Linux" ]]; then
    configure_xdebug_linux
  elif [[ "$(uname -s)" = "Darwin" ]]; then
    configure_xdebug_osx
  else
    echo "OS not supported" && exit 1
  fi
}

function configure_xdebug_linux() {
  if [[ -f "$(</proc/version)" && "$(</proc/version)" = "microsoft" ]]; then
    # If it's running in WSL
    XDEBUG_HOST=$(grep nameserver /etc/resolv.conf | cut -d ' ' -f2)
  fi

  # If it's running in Linux
  XDEBUG_HOST=$(hostname -I | cut -d ' ' -f1)

  # Adding your current IP to 'xdebug.client_host=' at xdebug.ini
  readonly XDEBUG_HOST
  sed -i "s/xdebug\.client_host\=.*/xdebug\.client_host\=${XDEBUG_HOST}/g" _infra/configs/xdebug.ini
}

function configure_xdebug_osx() {
     # If it's running in macOS
    XDEBUG_HOST=$(ipconfig getifaddr en0)
    readonly XDEBUG_HOST

    # Adding your current IP to 'xdebug.client_host=' at xdebug.ini
    sed -i "" -e "s/xdebug\.client_host\=.*/xdebug\.client_host\=${XDEBUG_HOST}/g" _infra/configs/xdebug.ini
}

function helper_commands() {
  if [[ "$1" = "artisan" ]]; then
    # Run an artisan command inside the app container.
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "cd ${WORKDIR} && php $*"

    # Adjusting permissions in case a files are created
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "chown 1000:1000 -R app"
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "chown 1000:1000 -R resources"
  fi

  if [[ "$1" = "tinker" ]]; then
    # Opening tinker (Laravel's REPL) inside the app container.
    docker-compose -f _infra/docker-compose.yml exec "${DOCKER_SERVICE_NAME}" sh -c "cd ${WORKDIR} && php artisan tinker"
  fi

  if [[ "$1" = "pest" ]]; then
    # Run an pest command inside the app container.
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "cd ${WORKDIR} && ./vendor/bin/$*"
  fi

  if [[ "$1" = "composer" ]]; then
    # Run an composer command inside the app container.
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "cd ${WORKDIR} && $*"
  fi
}

function docker_commands() {
  if [[ "$1" = "up" ]]; then
    docker-compose -f _infra/docker-compose.yml up
  fi

  if [[ "$1" = "down" ]]; then
    docker-compose -f _infra/docker-compose.yml down
  fi

  if [[ "$1" = "bash" ]]; then
    docker exec -it "${DOCKER_SERVICE_CONTAINER_NAME}" /bin/bash
  fi

  if [[ "$1" = "docker" ]]; then
    # Run Docker command through this script.
    "$@"
  fi

  if [[ "$1" = "clean-all" ]]; then
    printf "INFO: Destroying docker-compose resources \n"
    docker-compose -f _infra/docker-compose.yml down

    printf "\nINFO: Removing vendor directory \n"
    rm -rf vendor

    printf "\nINFO: Removing composer.lock \n"
    if [[ -f composer.lock ]]; then
      rm composer.lock
    fi

    printf "\nINFO: Killing any remaining containers \n"
    docker kill "$(docker ps -a | grep -i "${DOCKER_SERVICE_CONTAINER_NAME}" | awk '{print $1}')" || echo ""

    printf "\nINFO: Removing image \n"
    docker image rm -f "$(docker images | grep -i "$(basename "$(pwd)")" | awk '{print $1}')"

    printf "\nINFO: Removing volumes \n"
    readonly VOLUMES=$(docker volume ls | grep -i "$(basename "$(pwd)")" | awk '{print $2}')
    for volume in ${VOLUMES}; do
      docker volume rm -f "${volume}"
    done

    printf "\nINFO: Listing running containers \n"
    docker ps -a | grep -i "${DOCKER_SERVICE_CONTAINER_NAME}" || echo ""

    printf "\nINFO: Listing existing volumes \n"
    docker volume ls | grep -i "$(basename "$(pwd)")"
  fi

  if [ "$1" = "docker-compose" ]; then
    # Run docker-compose command through this script.
    "$@"
  fi
}

function continuous_integration() {
  if [[ "$1" = "tests" ]]; then
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "bin/tests.sh"
  fi

  if [[ "$1" = "linters" ]]; then
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "bin/linters.sh"
  fi

  if [[ "$1" = "fix-linters" ]]; then
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "bin/fix-linters.sh"
  fi

  if [[ "$1" = "static-analysis" ]]; then
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "bin/static-analysis.sh"
  fi

  if [[ "$1" = "update-dependencies" ]]; then
    docker-compose -f _infra/docker-compose.yml exec -T "${DOCKER_SERVICE_NAME}" sh -c "cd ${WORKDIR} && composer install"
  fi
}

function main() {
  configure_xdebug

  helper_commands "$@"
  docker_commands "$@"

  continuous_integration "$@"
}

main "$@"
